drop table user if exists;
create table user (id bigint generated by default as identity (start with 1), username varchar(255), mobile varchar(255), email varchar(255), nickname varchar(255), password varchar(255), valid boolean, primary key (id));
