SET DATABASE SQL SYNTAX MYS TRUE

drop table t_user if exists;
create table t_user
(
  id bigint generated by default as identity (start with 1) primary key,
  email varchar(255),
  mobile varchar(255),
  nickname varchar(255),
  password varchar(255),
  userLevel varchar(255),
  username varchar(255),
  memo varchar(255),
  valid boolean not null
);

drop table user_detail if exists;
create table user_detail (id bigint, address varchar(255), primary key (id));

drop table menu_01 if exists;
create table menu_01 (id integer generated by default as identity (start with 1), createTime timestamp, createUserId bigint, updateTime timestamp, updateUserId bigint, platform varchar(15), memo varchar(255), menuName varchar(255), parentId integer, valid boolean, primary key (id));
drop table menu if exists;
create table menu (id integer generated by default as identity (start with 1), createTime timestamp, createUserId bigint, updateTime timestamp, updateUserId bigint, platform varchar(15), memo varchar(255), menuName varchar(255), parentId integer, valid boolean, primary key (id));

drop table t_role if exists;
create table t_role(id bigint generated by default as identity (start with 1), ROLENAME VARCHAR(100) not null, ROLECODE VARCHAR(100) not null, VALID boolean DEFAULT TRUE, createTime timestamp, createUserId bigint, updateTime timestamp, updateUserId bigint);

drop table j_user_and_role if exists;
create table j_user_and_role (user_id bigint, role_id int, createUserId bigint);
alter table j_user_and_role add constraint j_user_and_role_unique_constraint unique (user_id, role_id);

drop table t_perm if exists;
CREATE TABLE t_perm
(
  id        bigint generated BY DEFAULT AS IDENTITY (start WITH 1) primary key,
  permName  VARCHAR(100) not null,
  valid     boolean DEFAULT TRUE
);

drop table j_role_and_perm if exists;
CREATE TABLE j_role_and_perm (role_id int, perm_id int);
alter table j_role_and_perm add constraint j_role_and_perm_unique_constraint unique (role_id, perm_id);
