drop table user if exists;
create table user (id bigint generated by default as identity (start with 1), username varchar(255), mobile varchar(255), email varchar(255), nickname varchar(255), password varchar(255), valid boolean, primary key (id));

INSERT INTO user (id, username, mobile, email, nickname, password, valid) VALUES (1, 'f0rb', '17778888881', 'f0rb@163.com', '测试1', '123456', true);
INSERT INTO user (id, username, mobile, email, nickname, password, valid) VALUES (2, 'user2', '17778888882', 'test2@163.com', '测试2', '123456', true);
INSERT INTO user (id, username, mobile, email, nickname, password, valid) VALUES (3, 'user3', '17778888883', 'test3@163.com', '测试3', '123456', true);
INSERT INTO user (id, username, mobile, email, nickname, password, valid) VALUES (4, 'user4', '17778888884', 'test4@163.com', '测试4', '123456', true);
