SET DATABASE SQL SYNTAX MYS TRUE;

drop table t_user if exists;
create table t_user (id bigint generated by default as identity (start with 1), username varchar(255), email varchar(255), mobile varchar(255), nickname varchar(255), password varchar(255), userLevel varchar(255), memo varchar(255), create_time timestamp, create_user_id bigint, update_time timestamp, update_user_id bigint, valid boolean not null, primary key (id));

INSERT INTO t_user (username, mobile, email, nickname, password, userLevel, valid) VALUES ('f0rb', '17778888881', 'test1@qq.com', '测试1', '123456', '高级', true);
INSERT INTO t_user (username, mobile, email, nickname, password, userLevel, valid) VALUES ('user2', '17778888882', 'test2@qq.com', '测试2', '123456', '普通', true);
INSERT INTO t_user (username, mobile, email, nickname, password, userLevel, valid) VALUES ('user3', '17778888883', 'test3@qq.com', '测试3', '123456', '普通', true);
INSERT INTO t_user (username, mobile, email, nickname, password, userLevel, valid) VALUES ('user4', '17778888884', 'test4@qq.com', '测试4', '123456', '普通', true);

drop table t_role if exists;
create table t_role(id bigint generated by default as identity (start with 1), role_name VARCHAR(100) not null, role_code VARCHAR(100) not null, VALID boolean DEFAULT TRUE, create_time timestamp, create_user_id bigint, update_time timestamp, update_user_id bigint);

INSERT INTO t_role (role_name, role_code) VALUES ('admin', 'ADMIN');
INSERT INTO t_role (role_name, role_code) VALUES ('vip', 'VIP');
INSERT INTO t_role (role_name, role_code) VALUES ('vip2', 'VIP2');
