name: Integration Test

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      docker-run:
        required: false
        type: string

jobs:
  test:
    name: Maven Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'adopt'
          cache: 'maven'
      - name: Log into Registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Set Image Name
        run: echo "IMAGE=ghcr.io/doytowin/doyto-query-image-${{ inputs.image-name }}:1" >> $GITHUB_ENV
      - name: Start Container
        run: ${{ inputs.docker-run }} -d ${{ env.IMAGE }}
      - name: Run Test
        run: mvn -B clean test -P docker,${{ inputs.image-name }}
      - name: Check log
        if: failure()
        run: docker logs ${{ inputs.image-name }}
