name: Integration Test

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      docker-run:
        required: true
        type: string

jobs:
  test:
    name: Maven Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache Embed Mongo distribution
        uses: actions/cache@v3
        with:
          path: ~/.embedmongo
          key: ${{ runner.os }}-mongo
          restore-keys: ${{ runner.os }}-mongo
      - name: Log into Registry ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Pull Image
        run: docker pull ghcr.io/doytowin/doyto-query-image-${{ inputs.image-name }}:main
      - name: Start Container
        run: ${{ inputs.docker-run }}
      - name: Run Test
        run: mvn -B clean test -P docker,${{ inputs.image-name }}
      - name: Check log
        if: failure()
        run: docker logs ${{ inputs.image-name }}
