name: Version

on:
  workflow_call:
    outputs:
      java:
        description: "The Java version"
        value: ${{ jobs.version.outputs.java }}

jobs:
  version:
    name: Determine Java version
    runs-on: ubuntu-latest
    env:
      VERSION: 8
    outputs:
      java: ${{ steps.version.outputs.java }}
    steps:
      - name: Switch Java version
        if: startsWith(github.ref, 'refs/heads/springboot3/')
        run: echo "VERSION=17" >> $GITHUB_ENV
      - id: version
        name: Write Java version
        run: echo "java=$VERSION" >> "$GITHUB_OUTPUT"
