name: GitHub Package

on:
  workflow_dispatch:
  push:
    branches:
      - package
      - v1/package

jobs:
  version:
    name: Determine Java version
    uses: doytowin/doyto-devops/.github/workflows/version_java17.yml@main
  package:
    needs: version
    name: Call Package Workflow
    uses: doytowin/doyto-devops/.github/workflows/package.yml@main
    secrets: inherit
    with:
      java-version: ${{needs.version.outputs.java}}
      repo: ${{ github.repository }}
