name: GitHub Package

on:
  workflow_dispatch:
  push:
    branches:
      - package
      - package/v2

jobs:
  version:
    name: Determine Java version
    runs-on: ubuntu-latest
    env:
      VERSION: 8
    outputs:
      java: ${{ steps.version.outputs.java }}
    steps:
      - name: Switch Java version
        if: github.ref == 'refs/heads/package/v2'
        run: echo "VERSION=17" >> $GITHUB_ENV
      - id: version
        name: Write Java version
        run: echo "java=$VERSION" >> "$GITHUB_OUTPUT"
  package:
    needs: version
    name: Call Package Workflow
    uses: doytowin/doyto-devops/.github/workflows/package.yml@main
    secrets: inherit
    with:
      java-version: ${{needs.version.outputs.java}}
      repo: ${{ github.repository }}
