name: GitHub Package

on:
  workflow_dispatch:
  push:
    branches: [ package ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Test
        run: mvn test
      - name: Publish to GitHub Packages Apache Maven
        run: mvn -DskipTests=true deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
